// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: test.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TestResponseSz uint64                 `protobuf:"varint,1,opt,name=test_response_sz,json=testResponseSz,proto3" json:"test_response_sz,omitempty"`
	Data           []uint64               `protobuf:"varint,2,rep,packed,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetTestResponseSz() uint64 {
	if x != nil {
		return x.TestResponseSz
	}
	return 0
}

func (x *TestRequest) GetData() []uint64 {
	if x != nil {
		return x.Data
	}
	return nil
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []uint64               `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *TestResponse) GetData() []uint64 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\x04test\"K\n" +
	"\vTestRequest\x12(\n" +
	"\x10test_response_sz\x18\x01 \x01(\x04R\x0etestResponseSz\x12\x12\n" +
	"\x04data\x18\x02 \x03(\x04R\x04data\"\"\n" +
	"\fTestResponse\x12\x12\n" +
	"\x04data\x18\x01 \x03(\x04R\x04data2\x90\x02\n" +
	"\vTestService\x122\n" +
	"\aTestRPC\x12\x11.test.TestRequest\x1a\x12.test.TestResponse\"\x00\x12@\n" +
	"\x13TestServerStreamRPC\x12\x11.test.TestRequest\x1a\x12.test.TestResponse\"\x000\x01\x12@\n" +
	"\x13TestClientStreamRPC\x12\x11.test.TestRequest\x1a\x12.test.TestResponse\"\x00(\x01\x12I\n" +
	"\x1aTestBidirectionalStreamRPC\x12\x11.test.TestRequest\x1a\x12.test.TestResponse\"\x00(\x010\x01B\tZ\a./;mainb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_proto_goTypes = []any{
	(*TestRequest)(nil),  // 0: test.TestRequest
	(*TestResponse)(nil), // 1: test.TestResponse
}
var file_test_proto_depIdxs = []int32{
	0, // 0: test.TestService.TestRPC:input_type -> test.TestRequest
	0, // 1: test.TestService.TestServerStreamRPC:input_type -> test.TestRequest
	0, // 2: test.TestService.TestClientStreamRPC:input_type -> test.TestRequest
	0, // 3: test.TestService.TestBidirectionalStreamRPC:input_type -> test.TestRequest
	1, // 4: test.TestService.TestRPC:output_type -> test.TestResponse
	1, // 5: test.TestService.TestServerStreamRPC:output_type -> test.TestResponse
	1, // 6: test.TestService.TestClientStreamRPC:output_type -> test.TestResponse
	1, // 7: test.TestService.TestBidirectionalStreamRPC:output_type -> test.TestResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
