// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: test.proto

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestService_TestRPC_FullMethodName                    = "/test.TestService/TestRPC"
	TestService_TestServerStreamRPC_FullMethodName        = "/test.TestService/TestServerStreamRPC"
	TestService_TestClientStreamRPC_FullMethodName        = "/test.TestService/TestClientStreamRPC"
	TestService_TestBidirectionalStreamRPC_FullMethodName = "/test.TestService/TestBidirectionalStreamRPC"
)

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceClient interface {
	TestRPC(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
	TestServerStreamRPC(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TestResponse], error)
	TestClientStreamRPC(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TestRequest, TestResponse], error)
	TestBidirectionalStreamRPC(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TestRequest, TestResponse], error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) TestRPC(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, TestService_TestRPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) TestServerStreamRPC(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[0], TestService_TestServerStreamRPC_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TestRequest, TestResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_TestServerStreamRPCClient = grpc.ServerStreamingClient[TestResponse]

func (c *testServiceClient) TestClientStreamRPC(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TestRequest, TestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[1], TestService_TestClientStreamRPC_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TestRequest, TestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_TestClientStreamRPCClient = grpc.ClientStreamingClient[TestRequest, TestResponse]

func (c *testServiceClient) TestBidirectionalStreamRPC(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TestRequest, TestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[2], TestService_TestBidirectionalStreamRPC_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TestRequest, TestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_TestBidirectionalStreamRPCClient = grpc.BidiStreamingClient[TestRequest, TestResponse]

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility.
type TestServiceServer interface {
	TestRPC(context.Context, *TestRequest) (*TestResponse, error)
	TestServerStreamRPC(*TestRequest, grpc.ServerStreamingServer[TestResponse]) error
	TestClientStreamRPC(grpc.ClientStreamingServer[TestRequest, TestResponse]) error
	TestBidirectionalStreamRPC(grpc.BidiStreamingServer[TestRequest, TestResponse]) error
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestServiceServer struct{}

func (UnimplementedTestServiceServer) TestRPC(context.Context, *TestRequest) (*TestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestRPC not implemented")
}
func (UnimplementedTestServiceServer) TestServerStreamRPC(*TestRequest, grpc.ServerStreamingServer[TestResponse]) error {
	return status.Error(codes.Unimplemented, "method TestServerStreamRPC not implemented")
}
func (UnimplementedTestServiceServer) TestClientStreamRPC(grpc.ClientStreamingServer[TestRequest, TestResponse]) error {
	return status.Error(codes.Unimplemented, "method TestClientStreamRPC not implemented")
}
func (UnimplementedTestServiceServer) TestBidirectionalStreamRPC(grpc.BidiStreamingServer[TestRequest, TestResponse]) error {
	return status.Error(codes.Unimplemented, "method TestBidirectionalStreamRPC not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}
func (UnimplementedTestServiceServer) testEmbeddedByValue()                     {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	// If the following call panics, it indicates UnimplementedTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_TestRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).TestRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_TestRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).TestRPC(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_TestServerStreamRPC_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TestRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServiceServer).TestServerStreamRPC(m, &grpc.GenericServerStream[TestRequest, TestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_TestServerStreamRPCServer = grpc.ServerStreamingServer[TestResponse]

func _TestService_TestClientStreamRPC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).TestClientStreamRPC(&grpc.GenericServerStream[TestRequest, TestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_TestClientStreamRPCServer = grpc.ClientStreamingServer[TestRequest, TestResponse]

func _TestService_TestBidirectionalStreamRPC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).TestBidirectionalStreamRPC(&grpc.GenericServerStream[TestRequest, TestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_TestBidirectionalStreamRPCServer = grpc.BidiStreamingServer[TestRequest, TestResponse]

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestRPC",
			Handler:    _TestService_TestRPC_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TestServerStreamRPC",
			Handler:       _TestService_TestServerStreamRPC_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TestClientStreamRPC",
			Handler:       _TestService_TestClientStreamRPC_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "TestBidirectionalStreamRPC",
			Handler:       _TestService_TestBidirectionalStreamRPC_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "test.proto",
}
